{
 "title": "AAISP",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "LineID", "label": "Line ID", "query": { "query": "label_values(LineID)" } }
  ]
 },
 "panels": [
  {
   "title": "Quota (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "LineID",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "monthly_allowance_remaining{LineID=\"$LineID\"} / monthly_allowance {LineID=\"$LineID\"}",
     "legendFormat": "Line: {{LineID}}"
    }
   ]
  },
  { "title": "Per-Line Specifics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "LineID" },
  {
   "title": "Stream Rates",
   "type": "gauge",
   "description": "Down- and up-stream rate for the line. Adjusted is post ate-limiting and the ilk.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "downstream_sync_rate{LineID=\"$LineID\"}",
     "legendFormat": "Downstream (Raw)"
    },
    {
     "expr": "downstream_rate_adjusted{LineID=\"$LineID\"}",
     "legendFormat": "Downstream (Adjusted)"
    },
    {
     "expr": "upstream_sync_rate{LineID=\"$LineID\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "Quota (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "monthly_allowance_remaining{LineID=\"$LineID\"} / monthly_allowance {LineID=\"$LineID\"}",
     "legendFormat": "Line: {{LineID}}"
    }
   ]
  },
  {
   "title": "Data Allowance",
   "type": "timeseries",
   "description": "Data allowance for this month. Remaining may be higher than quota, due to rollover of unused quota.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monthly_allowance_remaining{LineID=\"$LineID\"}",
     "legendFormat": "Remaining (Line: {{LineID}})"
    },
    {
     "expr": "monthly_allowance{LineID=\"$LineID\"}",
     "legendFormat": "Quota (Line: {{LineID}})"
    }
   ]
  }
 ]
}