name: build-aaisp-exporter

on:
  push:
    branches: [ add-actions ]
  pull_request:
    branches: [ add-actions ]

jobs:

  build:
    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Build
        run: go build -v ./...

      - name: Collect binaries
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary
          path: |
            aaisp-exporter
            aaisp-exporter.exe
          if-no-files-found: error
          retention-days: 1
